# Generated by Django 3.2.3 on 2021-05-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
