# Generated by Django 3.2.3 on 2021-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_alter_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(),
        ),
    ]
