# Generated by Django 3.2.3 on 2021-05-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0015_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
