# Generated by Django 3.2.3 on 2021-05-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0019_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='relatedimage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imagecomments', to='instaclone.image'),
        ),
    ]
