# Generated by Django 3.2.3 on 2021-05-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0020_comment_relatedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
