# Generated by Django 3.2.3 on 2021-05-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0021_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('relatedimage', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imagecomments', to='instaclone.image')),
            ],
        ),
    ]
