# Generated by Django 3.2.3 on 2021-05-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0022_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='relatedimage',
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='instaclone.comment'),
        ),
    ]
