# Generated by Django 3.2.3 on 2021-05-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0023_auto_20210524_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(),
        ),
    ]
